### ISSUE TITLE
Create Cloud Foundry application in IBM Cloud

### ISSUE THREAD

**Issue by ethankessinger** [customers-devops-2019/customers#50] opened 2019-04-09 15:35 UTC
**As a** developer
**I need** to set up Cloud Foundry
**So that** I will be able to deploy my app to the cloud

**Assumptions:**
* Name IBM Cloud microservice: nyu-customer-service-s19
* There should be at least 2 instances

**Acceptance Criteria:**
When I create the app in IBM Cloud
Then I do not get any errors, the status should be running and I should be able to visit it at: nyu-customer-service-s19.mybluemix.net

**Comment by itsAnth** [comment] 2019-04-12 00:52
Duplicate of issue 57 since it is created when we push up to cf

**Closed as completed** 2019-04-12 18:19 UTC
Labels: duplicate
